Issue/387
traPtitech/knoQ-UI pull request #498
Opened 2021-09-05 12:04 UTC by itt828

2021-09-05 14:14 UTC, fuji8 commented
ui側ではアバターが`trap`であることは分からないので、`TrapAvator`の名前を`trap`に限らないような名前にしてください

2021-09-06 08:53 UTC, wasabi315 requested changes
@fuji8の指摘に追加で，TrapAvatarコンポーネントのプロパティ`trap-id`も`user-id`のようにするといいと思います．それ以外は良さです！

2021-09-09 07:51 UTC, wasabi315 approved these changes
LGTM:+1:

2021-09-09 07:52 UTC, wasabi315 commented
fixes #387

2021-09-09 11:18 UTC, merged