進捗部屋登録_ボタンとフォームの表示
traPtitech/knoQ-UI pull request #894
Opened 2023-08-09 14:19 UTC by mathsuky

進捗部屋登録のタスクを進めました。
ここまでで，進捗部屋登録の項目をサイドバーに作ること，ボタンを押すとフォームを表示すること，ユーザーからのデータを受け取ること，までを一旦実装しました。
いくつか質問があります。
1.進捗部屋登録の項目をサイドバーに作って良いのか(もっと目立たない場所におくべき?)
2.adminのみが編集できるようにするにはどうすれば良いのか
3.受け取った入力をどう処理すればいいのか
上記以外にもコードの書き方等含めて指摘いただけるとありがたいです。
以上,よろしくお願いします。

2023-08-18 11:44 UTC, itt828 commented
1. 部屋についてのページ(確保した進捗部屋をリスト形式で表示など)を将来的に作る予定ならサイドバーに項目を生やしてもいいかもしれないです。そうでない場合はサイドバー内のフッターあたりに生やすのが妥当かなと思っています。@Kami-jo と相談して決めたいです。
2. responseUserにprevilagedというフィールドがあるのでそれを使うといいです。
3.  `addAllRooms`関数が`あるのでこれを使うといいです。使い方は`pages/EventNew.vue`のような、同様にapiを叩いてる箇所を参考にしてみてください:pray:

2023-08-18 12:20 UTC, itt828 commented
バリデーションについては、

- 送信前は、今実装されている6列のcsvになっているかのバリデーションのみを行う
- APIを叩いて400番台が返ってきたらエラーを表示する

以上の方針でお願いします。

2023-08-22 12:29 UTC, mathsuky commented
リネームとAPI周りの仮実装をしました。方向性がこれで良ければデザインなどの修正をします。
一つ質問なのですが，登録をするのにadminsを投げなければいけないと思うのですが，誰をadminにすれば良いのでしょうか。単に登録をしているユーザー一人にすべきか,それとも担当の人全員分などにすべきでしょうか。

2023-08-24 01:17 UTC, itt828 requested changes

2023-08-24 04:39 UTC, mathsuky commented on src/pages/VerifiedRoom.vue
> +            end_date: columns[3],
すみません，これがよくわからないのですが，最初の行のデータの順番を受け取るということですか？(例えばsubject,start_date,end_date,place,...という順番になってたら，そのように受け取り方を変える)。もしそうだとした時，それをどう実現して良いかがわからないです。

2023-08-24 08:12 UTC, Kami-jo commented on src/pages/VerifiedRoom.vue
> +        </div>
権限が無いユーザーにはインタラクションを表示しないのが一般的な気がしてる

2023-08-24 08:13 UTC, Kami-jo commented on src/pages/VerifiedRoom.vue
> +        </div>
ソースあったわ
https://smarthr.design/products/design-patterns/access-control-pattern/#h2-0

2023-08-24 08:50 UTC, itt828 commented on src/pages/VerifiedRoom.vue
> +        </div>
僕もそう思いましたが、そうすると非特権ユーザーには/workspaceが何も表示されないページになってしまうので上の対応を考えました。

- 将来的にこのページに進捗部屋の一覧などを実装することを見越してインタラクションを表示しない
- 進捗部屋の一覧などは実装しないことにしてページも切らない(サイドバーの下部等に特権ユーザーだけ表示されるアイコンを表示してクリックするとモーダルが出るなど)

のような対応もあるかなと思っています。

2023-08-24 08:55 UTC, itt828 commented on src/components/main/SidebarNavigation.vue
> +      },
アイコン何にするか決めないとか
↓のリンクから提案してくれるとうれしいです。
https://pictogrammers.com/library/mdi/

2023-08-25 00:59 UTC, itt828 commented on src/pages/VerifiedRoom.vue
> +            end_date: columns[3],
> 最初の行のデータの順番を受け取るということですか？(例えばsubject,start_date,end_date,place,...という順番になってたら，そのように受け取り方を変える)。

合ってます。

実装の方法としては、先頭行のカラム名と何列目という数字のマップを作成しておき、2行目以降のパース時に用いる、などができると思います。

実は修正を指示しておいてなんですが、csvを自力でパースするのは難しいので、ライブラリを探して利用するか、いいライブラリが見つからない場合はバリデーションは実装せずサーバーサイドに投げてしまうのでもいいかなと思います。

2023-08-25 04:31 UTC, mathsuky commented on src/pages/VerifiedRoom.vue
> +            end_date: columns[3],
了解しました。細かく説明していただきありがとうございます!

2023-08-26 07:49 UTC, mathsuky commented
fetchAPIへの変更と細々した変更をしました。確認をお願いします🙏
2つ質問があります。
1.fetchAPIを試そうとするとCORSが出てしまうのですが，回避する方法はありますか。なろうなどではバックエンドを修正した記憶がありますが，それをする必要があるのでしょうか。
2.csvのパースについて，fetchAPIでcsvを投げる時はこういう列の順番に変えて投げなければいけない，というのがあるのでしょうか。あるとすれば，それはSwaggerに載っている例？みたいなものの順番で良いのでしょうか。
csvのパースについては，これを見てもらった後にcsv-parseなどを用いて実装できないかと考えています。
よろしくお願いします。

2023-08-26 22:52 UTC, itt828 commented on src/pages/VerifiedRoom.vue
> +        </div>
@Kami-jo おてすきの際に返信ください

2023-08-27 01:06 UTC, itt828 requested changes
改善ありがとうございます！

新しく気づいたことなど、いくつかコメントしました。
確認お願いします

2023-08-27 01:06 UTC, itt828 commented on src/pages/VerifiedRoom.vue
> +      const columns = rows.map(row => row.split(','))
csvはダブルクオーテーションでフィールドを囲って内部でコンマを使用することができるので、この分割の仕方だと正確にパースできない場合があります。
前回のコメントの通り、csvのパースは難しいので、ライブラリに頼れない場合はバリデーションしないのが無難です。

2023-08-27 03:18 UTC, mathsuky commented
確認ありがとうございます！すみません，コメント書き忘れてました...
1点質問なのですが，fetchAPIを叩くとCORSなど認証周りのエラーが出てしまうのですが，回避する方法はありますか？なろうのときなどはバックエンドをいじった記憶があるのですが，そうすべきなのでしょうか。

2023-08-27 22:13 UTC, itt828 commented
/rooms/allにpostするにはprivilegedなユーザーである必要がありますが、開発環境のknoQでprivilegedなユーザーになっていないかもしれないです。privilegedなユーザーになるにはDBの値を直接変更する必要があります。
以下の手順でできます。
1. サーバーの開発環境をdocker composeで立ち上げる
2. localhost:8000 にブラウザでアクセスする
    - phpmyadminというのが見られると思います
3. userのテーブルから自身のレコードを見に行き、privilegedの値を1に変更

2023-08-31 02:37 UTC, mathsuky commented
以前指摘していただいた部分の修正と，csvのパースの実装をしました。csvのパースには，csv-parse(https://www.npmjs.com/package/csv-parse)というものを使いました。
コンフリクトしてしまったので修正できそうあれば修正します。

2023-08-31 02:49 UTC, mathsuky commented
以前指摘していただいた部分の修正とcsvのパースの実装をしました。csvのパースにはcsv-parseというものを使いました。確認よろしくお願いします🙇
https://www.npmjs.com/package/csv-parse
csv-parseを使うためにいくつかインストールしたところの周りでコンフリクトしてしまったのですが，どっちを残せばよいのかよくわからなかったので，アドバイスいただけるとありがたいです。
よろしく願いします。

2023-09-03 14:19 UTC, itt828 commented
PRとコミットありがとうございます！手元で実行したところかなりいい感じになってました。
ひとつ追加でお願いしたいことがあります。
集会で上条さんと話し合った結果、進捗部屋登録ボタンは以前に言及したような、サイドバーの下部(はてなアイコンの隣)に配置し、進捗部屋の情報はカレンダーに置くのが良いだろうという結論になりました。

つきましては、このように実装しなおしてくれると助かります:bowing_man::bowing_man::bowing_man:

2023-09-07 06:51 UTC, mathsuky commented
進捗部屋登録のボタンをサイドバーの下に移しました。これで良さそうであれば，もともと作ってた部分を削除します。
一点，もともとのコードのscript部分をかなり変更したので，不都合が生じそうであれば教えていただきたいです。
よろしくお願いします🙏

2023-09-07 08:04 UTC, mathsuky commented
細かい表示を修正しました。
エラーメッセージについて，バリデーションの内容もrules.tsに追加するのが良いような感じがするのですが，rules.tsでバリデーション判定をする・SidebarFooter.vueからshowErrorを持ってきて判定するという方法では，処理にズレが生じてうまくエラーメッセージが意図するタイミングで表示されませんでした。バリデーション周りのエラー表示は今のままで良いでしょうか。

2023-09-12 00:43 UTC, mathsuky commented on src/main.ts
> +window.Buffer = window.Buffer || Buffer
以前はcsv-parse/syncからcsv-parseを持ってきていて，そのときにはこれがないと動きませんでした。csv-parse/browser/esm/syncにするとなくても動くのですが，消し忘れていました🙏消しておきます。

2023-09-12 00:46 UTC, mathsuky commented on src/components/main/SidebarFooter.vue
> +            body: records,
実は一度rules.tsで判定するようにしたのですが，そうすると挙動がおかしかった(入力がいいタイミングで判定されなかった)ような気がします。もう一度試してみます。

2023-09-13 15:55 UTC, mathsuky commented
指摘していただいた部分をいくつか修正しました。
データをpostするとき，this.inputDataをそのまま投げると複数行の場合にエラーが出るという問題があることと，package.jsonの変更はテストで弾かれてしまうことについてはもう少し原因を探ってみます。
2日ほど作業出来なさそうなので，取り急ぎ出来た分部分だけ上げました。よろしくお願いします。

2023-09-13 16:05 UTC, itt828 commented
`yarn`してyarn.lockをpushしてみてください

2023-09-13 16:21 UTC, itt828 commented
もう一回yarnしてみてください　多分bufferのパッケージ消す前にやってますよね

2023-09-17 12:58 UTC, mathsuky commented
this.inputDataが複数行の場合エラーが返ってくる問題について，データがcsv形式であることを明示的にすれば良いのではないかと考えてそのようなライブラリを導入したところ,一応投げる際にエラーが出ることは無くなりました。
ただ，うまくデータベースに反映されてる感じがなく，うまくいっていない気がします。
自分では手詰まりになってしまったので，どのような形で投げればデータが反映されるのか，助言をいただけるとありがたいです🙏お忙しい中申し訳ありませんが，よろしくお願いします。

2023-09-19 01:26 UTC, itt828 requested changes

2023-09-19 01:26 UTC, itt828 commented on src/components/main/SidebarFooter.vue
> +    },
この関数はここではなくworkers以下にファイルを作ってそこに置いてほしいです。

2023-09-19 01:26 UTC, itt828 commented on src/components/main/SidebarFooter.vue
> +            body: csvData,
```suggestion
            body: this.inputData,
```
で私の場合は正常にデータを送信できたのですが、そちらの環境でどのようなエラーが生じているか、また、devtoolsのネットワークタブを見てリクエストとレスポンスの内容がどのようになっていたかを教えていただきたいです。

2023-09-19 02:43 UTC, mathsuky commented on src/components/main/SidebarFooter.vue
> +            body: csvData,
![スクリーンショット 2023-09-19 11 41 08](https://github.com/traPtitech/knoQ-UI/assets/93627045/19f82bf1-d7d9-4d52-b8f2-6e6088ad66b8)
ここの情報で十分でしょうか。this.inputDataが複数行に渡るデータの場合，400が返ってくる問題が起きています。

2023-09-19 02:53 UTC, itt828 commented on src/components/main/SidebarFooter.vue
> +            body: csvData,
ありがとうございます
できればペイロードの方も見たいです

2023-09-19 03:25 UTC, mathsuky commented on src/components/main/SidebarFooter.vue
> +            body: csvData,
![スクリーンショット 2023-09-19 12 23 39](https://github.com/traPtitech/knoQ-UI/assets/93627045/a172091b-95a2-434f-9048-b2b94c381c07)
遅くなりすみません。こちらで大丈夫でしょうか。

2023-09-19 03:27 UTC, mathsuky commented
isValidData.tsというファイルを作成し，そこで定義した関数を利用するように変更しました。

2023-09-19 04:10 UTC, mathsuky commented
不必要になった部分を削除しました。

2023-09-21 00:35 UTC, itt828 requested changes
期待する通りに動くようになっていて感動しました！
いくつか細かい修正をお願いします:pray:

2023-09-21 05:01 UTC, mathsuky commented
指摘していただいた部分について修正しました。
一点質問なのですが，`relax_column_count`のオプションを外すと例えば6列5列の2行からなるデータが与えられた時，rulesの警告がうまく表示されないという問題が自分の手元では起こるのですが，どうでしょうか。
一旦その部分の修正は保留にしてあります。

2023-09-24 11:50 UTC, itt828 approved these changes
LGTM

2023-09-24 12:17 UTC, wasabi315 approved these changes
LGTM

2023-09-24 12:22 UTC, merged